language: python
python:
  - "3.6"

# install dependencies
install:
  - pip install -r flowey-server/requirements.txt

before_script:
  - cd flowey-server
script:
  - FLASK_APP=flasky.py flask test --coverage
