language: python
python:
  - '3.6'
install:
  - pip install -r flowey-server/requirements.txt

script:
  - ./test.sh

after-success:
  - mv `git ls-files -o -x reports` reports/

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: test-reports
  local-dir: reports
  on:
    branch: master

